# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Record patterns don't improve the readability of the code necessarily.
- ignore: {name: "Use record patterns"}

# In the renaming module substitutions are modeled as functions.
# The usage of lambda abstractions actually improves the readability.
- ignore: {name: "Redundant lambda", within: ["HST.Environment.Renaming"]}

# When reporting errors and in the test suite we are using `$` and `do` to
# format code correctly.
- ignore: {name: "Redundant $"}
- ignore: {name: "Redundant do"}

# Duplication makes the test code easier to read.
- ignore: {name: "Reduce duplication", within: ["HST.Effect.ReportTests"]}

# Aliases for qualified imports.
- modules:
  - {name: [ Data.Set ], as: Set}
  - {name: [ Data.Set.Ordered ], as: OSet}
  - {name: [ Data.Map.Strict ], as: Map}
  - {name: [ HST.Frontend.GHC.From ], as: FromGHC}
  - {name: [ HST.Frontend.GHC.To ], as: ToGHC}
  - {name: [ HST.Frontend.HSE.From ], as: FromHSE}
  - {name: [ HST.Frontend.HSE.To ], as: ToHSE}
  - {name: [ HST.Frontend.Syntax ], as: S}
  - {name: [ Language.Haskell.Exts ], as: HSE}
  - {name: [ Test.HUnit.Base ], as: HUnit}
