# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Record patterns don't improve the readability of the code necessarily.
- ignore: {name: "Use record patterns"}

# In the renaming module substitutions are modeled as functions.
# The usage of lambda abstractions actually improves the readability.
- ignore: {name: "Redundant lambda", within: ["HST.Environment.Renaming"]}

# Aliases for qualified imports.
- modules:
  - {name: [ HST.CoreAlgorithm ], as: CA}
  - {name: [ HST.Frontend.Syntax ], as: S}
  - {name: [ HST.Frontend.FromHSE ], as: FromHSE}
  - {name: [ HST.Frontend.ToHSE ], as: ToHSE}
